### ISSUE TITLE
status fails while check-for-updates is running

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/kastenwesen#32]
The temporary container instance started for check-for-updates triggers an error in `status`.
The same problem is probably for `shell --new-instance`.

```
Traceback (most recent call last):
  File "/usr/local/bin/kastenwesen", line 835, in <module>
    main()
  File "/usr/local/bin/kastenwesen", line 781, in main
    print_status_and_exit(given_containers)
  File "/usr/local/bin/kastenwesen", line 718, in print_status_and_exit
    if status_many(given_containers):
  File "/usr/local/bin/kastenwesen", line 626, in status_many
    container_okay = container.print_status(sleep_before=False)
  File "/usr/local/bin/kastenwesen", line 272, in print_status
    running = self.is_running()
  File "/usr/local/bin/kastenwesen", line 475, in is_running
    self.check_for_unmanaged_containers()
  File "/usr/local/bin/kastenwesen", line 472, in check_for_unmanaged_containers
    raise Exception("The container '{}', not managed by kastenwesen.py, is currently running from the same image '{}'. I am assuming this is not what you want. Please stop it yourself and restart it via kastenwesen. See the output of 'docker ps' for more info.".format(container['Id'], self.image_name))
Exception: The container '570890a87f7cb086ed94cf32747c41582658f311c3236a71652d96085301eb60', not managed by kastenwesen.py, is currently running from the same image 'appserver:latest'. I am assuming this is not what you want. Please stop it yourself and restart it via kastenwesen. See the output of 'docker ps' for more info.
```

**Comment by patkan** [comment]
But why did this not happen earlier? I can not remember this happening before...

**Comment by patkan** [comment]
How about we write the running containers of `status` into a redis or a file as a 'whitelist'?

**Comment by mgmax** [comment]
The code paths for locking and sleep were changed recently. As this is a race condition, any minor timing difference can make the problem appear or disappear.

Currently, many operations in `kastenwesen status` are not made for executing in parallel with another running instance.

**Comment by patkan** [comment]
Cool, I did not know `labels`. :-)
